### ISSUE TITLE
Bug in module source reading

### ISSUE THREAD

**Issue by n0str** [codex-team/hawk.python#12]
```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bot/bot/venv/lib/python3.6/site-packages/aiohttp/web_protocol.py", line 417, in start
    resp = yield from self._request_handler(request)
  File "/home/bot/bot/venv/lib/python3.6/site-packages/aiohttp/web.py", line 289, in _handle
    resp = yield from handler(request)
  File "/home/bot/bot/applications/github/github/sdk/lib/server.py", line 31, in wrapper
    self.sdk.hawk.catch()
  File "/home/bot/bot/venv/lib/python3.6/site-packages/hawkcatcher/__init__.py", line 108, in catch
    self.handler(*sys.exc_info())
  File "/home/bot/bot/venv/lib/python3.6/site-packages/hawkcatcher/__init__.py", line 80, in handler
    callee['sourceCode'] = self.get_near_filelines(callee['file'], callee['line'])
  File "/home/bot/bot/venv/lib/python3.6/site-packages/hawkcatcher/__init__.py", line 120, in get_near_filelines
    with open(filepath, 'r') as file:
FileNotFoundError: [Errno 2] No such file or directory: '/home/bot/bot/applications/github/github/multidict/_multidict.pyx'
```

**Comment by theArtechnology** [comment]
no resolution for that ?
